[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#bb9e55"
backgroundColor = "#f4f1e8"
secondaryBackgroundColor = "#ffffff"
textColor = "#26231f"
